spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000ms
  redis:
    host: 39.106.23.93
    port: 6379
    database: 5
    password: 123456
logging:
  level:
    root: info